version: 0.2
 
phases:
  install:
    runtime-versions:
        nodejs: 18
    commands:
        - echo Installing dependencies...
        - npm install
 
artifacts:
  files:
    - '**/*'
  discard-paths: yes